version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: skinxpert_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "skinXpert"
      TZ: "Europe/Madrid"
    command: --default-time-zone='Europe/Madrid'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./skinXpertBD.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skinxpert_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-red:
    build: ./node-red
    container_name: skinxpert_nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
      - ./skin.json:/data/flows.json
      - "./uploads:/usr/share/nginx/html/uploads"
    networks:
      - skinxpert_network
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: skinxpert_web
    ports:
      - "8080:80"
    volumes:
      - "./src/main/webapp:/usr/share/nginx/html"
      - "./uploads:/usr/share/nginx/html/uploads"
    networks:
      - skinxpert_network
    depends_on:
      - node-red


  sonar-db:
    image: postgres:13
    container_name: skinxpert_sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - skinxpert_network


  sonarqube:
    image: sonarqube:community
    container_name: skinxpert_sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - skinxpert_network
    depends_on:
      - sonar-db

  skinxpert_ai:
    build: ./IA  
    container_name: skinxpert_ai
    restart: unless-stopped
    networks:
      - skinxpert_network
      
  operating:
    build: 
      context: .
      dockerfile: Dockerfile.operating
    container_name: skinxpert_operating
    ports:
      - "8082:8082"
    networks:
      - skinxpert_network
volumes:
  mysql_data:
    driver: local
  nodered_data:
  postgresql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  skinxpert_network:
    driver: bridge